include "Buildfile.defs";

var object_dir			$=	libjr/alist
var proj_cflags			$=

var target_libs			$=	libjr
var target_progs		$=

var source_list			$=	alist.c alistadd.c alistdel.c alistfnd.c \
							alistpfx.c alistsrt.c alistcmp.c


jr_add_lib_default_rules	(target_progs, target_libs, proj_cflags, object_dir, COMPILE_STYLE);

jr_add_lib_rule			("libjr", source_list, COMPILE_STYLE);
