include "Buildfile.defs";

var object_dir			$=	libjr/avl_tree
var proj_cflags			$=

var target_libs			$=	libjr
var target_progs		$=	tst_avl
var link_libs			$=	libjr
var link_args			$=

var source_list			$=	avl_tree.c avl_del.c avl_find.c avl_indx.c avl_ins.c \
							avl_path.c avl_pfx.c avl_prnt.c avl_trav.c



jr_add_lib_default_rules	(target_progs, target_libs, proj_cflags, object_dir, COMPILE_STYLE);

jr_add_lib_rule			("libjr", source_list, COMPILE_STYLE);
jr_add_prog_rule			("tst_avl", "tst_avl.c", link_libs, link_args, COMPILE_STYLE);
