include "Buildfile.defs";

var object_dir			$=	libjr/dlist
var proj_cflags			$=

var target_libs			$=	libjr
var target_progs		$=	tst_dlst
var link_libs			$=	libjr
var link_args			$=

var source_list			$=	dlist.c dlistadd.c dlistcmp.c dlistdel.c \
							dlistpfx.c dlistsrt.c


jr_add_lib_default_rules	(target_progs, target_libs, proj_cflags, object_dir, COMPILE_STYLE);

jr_add_lib_rule			("libjr", source_list, COMPILE_STYLE);
jr_add_prog_rule			("tst_dlst", "tst_dlst.c", link_libs, link_args, COMPILE_STYLE);
