include "Buildfile.defs";

var object_dir			$=	libjr/htable
var proj_cflags			$=

var target_libs			$=	libjr
var target_progs		$=
var link_libs			$=	libjr
var link_args			$=

var source_list			$=	htable.c htabldel.c htablemt.c htablins.c \
							htablpfx.c htablsts.c 

jr_add_lib_default_rules	(target_progs, target_libs, proj_cflags, object_dir, COMPILE_STYLE);

jr_add_lib_rule			("libjr", source_list, COMPILE_STYLE);

